# Generated by Django 5.1.4 on 2024-12-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0002_gallery_allowed_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
