---
services:
  db:
    image: docker.io/postgres:17.2
    container_name: postgres-eventpics
    environment:
      POSTGRES_USER: "${EVENTPICS_DB_USER}"
      POSTGRES_PASSWORD: "${EVENTPICS_DB_PASSWORD}"
      POSTGRES_DB: "${EVENTPICS_DB_NAME}"
    expose:
      - "5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  eventpics:
    # Uncomment to build in development
    # build: ../eventpics
    image: ghcr.io/dbrennand/eventpics:0.1.0
    container_name: eventpics
    environment:
      EVENTPICS_SECRET_KEY: "${EVENTPICS_SECRET_KEY}"
      EVENTPICS_DEBUG: "${EVENTPICS_DEBUG}"
      EVENTPICS_DB_NAME: "${EVENTPICS_DB_NAME}"
      EVENTPICS_DB_USER: "${EVENTPICS_DB_USER}"
      EVENTPICS_DB_PASSWORD: "${EVENTPICS_DB_PASSWORD}"
      EVENTPICS_DB_HOST: "${EVENTPICS_DB_HOST}"
      EVENTPICS_ALLOWED_HOSTS: "${EVENTPICS_ALLOWED_HOSTS}"
      EVENTPICS_ENABLE_SECURE_PROXY_SSL_HEADER: "${EVENTPICS_ENABLE_SECURE_PROXY_SSL_HEADER}"
      EVENTPICS_CSRF_COOKIE_SECURE: "${EVENTPICS_CSRF_COOKIE_SECURE}"
      EVENTPICS_SESSION_COOKIE_SECURE: "${EVENTPICS_SESSION_COOKIE_SECURE}"
      DJANGO_SUPERUSER_PASSWORD: "${DJANGO_SUPERUSER_PASSWORD}"
      DJANGO_SUPERUSER_EMAIL: "${DJANGO_SUPERUSER_EMAIL}"
      DJANGO_SUPERUSER_USERNAME: "${DJANGO_SUPERUSER_USERNAME}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_STORAGE_BUCKET_NAME: "${AWS_STORAGE_BUCKET_NAME}"
      AWS_S3_REGION_NAME: "${AWS_S3_REGION_NAME}"
      AWS_S3_ENDPOINT_URL: "${AWS_S3_ENDPOINT_URL}"
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
        restart: true

  caddy:
    image: docker.io/caddy:2.8.4-alpine
    container_name: caddy
    volumes:
      - ./conf:/etc/caddy
      - caddy_data:/data
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    depends_on:
      - db
      - eventpics

volumes:
  pg_data:
  caddy_data:
